### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by 0xhams02** [VisonM/miniprogram#2]
你好，我运行小程序后报一下错误，是否为提供数据库文件？
应该是缺少云数据库各个数据库的名称。能否提供下？

**Comment by bigbossx** [comment]
[数据.json.zip](https://github.com/VisonM/miniprogram/files/6692477/json.zip)


> 你好，我运行小程序后报一下错误，是否为提供数据库文件？
> 应该是缺少云数据库各个数据库的名称。能否提供下？

**Comment by mivanzhang** [comment]
@zenghangyu 请教大佬，这个数据库文件可以使用吗？我导入数据提示报错，
